### ISSUE TITLE
rickyreusser.com DNS does not resolve

### ISSUE THREAD

**Issue by rreusser** [rreusser/plotly-mock-viewer#16]
No plans to renew it. Have removed CNAME from https://github.com/rreusser/rreusser.github.io. Perhaps it'll resolve itself in a few minutes?

**Comment by etpinard** [comment]
https://rreusser.github.io/plotly-mock-viewer/ now works

Thanks for headsup @rreusser :tada:

**Comment by rreusser** [comment]
No prob. As always, just let me know if you want to transfer ownership or need other maintenance/action, but otherwise assuming all good 🎉
