### ISSUE TITLE
Add compress_attributes.js transform

### ISSUE THREAD

**Issue by rreusser** [rreusser/plotly-mock-viewer#5]
To trim attr descriptions.

**Comment by etpinard** [comment]
After thinking about this some more, maybe plotly.js should compress its attributes _by default_. That is, we should list the compress attribute transform in its package.json. 

At the time of the first plotly.js FOSS release, I wasn't aware of the [`--ignore-transform=MODULE`](https://github.com/substack/node-browserify#usage) browserify option. I'm thinking by default we should :hocho: the attribute descriptions by default and allow users to optionally include them in custom builds. Thoughts?

**Comment by rreusser** [comment]
Strong agreement. Was wondering about this as I realized my custom bundles are giant because I'm not bothering to pull in that transform.

**Comment by etpinard** [comment]
> Strong agreement.

Awesome. I'll put that on my todo list. Feel free to close this issue :+1:

**Comment by rreusser** [comment]
No prob. Are you able to close the issue? I can, but curious if non-org-owner permissions (there is no org) include managing other functions.

**Comment by etpinard** [comment]
... I think so.
